### ISSUE TITLE
New Pico Plus 2 W LED problem

### ISSUE THREAD

**Issue by leonheller** [pimoroni/pimoroni-pico-rp2350#11]
Can't get onboard LED on new Pico Plus 2 W to work. Confirmed by another user on the forum.

**Comment by Gadgetoid** [comment]
Yup, I appear to have mucked this up trying to avoid having two many different builds for PPP2 and PPP2W.

Try: https://github.com/pimoroni/pimoroni-pico-rp2350/actions/runs/11104523856/artifacts/1994953669

You will need to use `machine.Pin("LEDW")` for frustratingly awkward reasons.

**Comment by helgibbons** [comment]
Some example code in #12 that should hopefully help with this :)

**Comment by leonheller** [comment]
Thanks, 

Philip Howard sent me a new version of MicroPython that had the problem fixed.


Regards, 

Leon
