### ISSUE TITLE
Proper Pico 2 W Wifi Support

### ISSUE THREAD

**Issue by justin-luoma** [pimoroni/pimoroni-pico-rp2350#17]

**Comment by Gadgetoid** [comment]
What is meant by "proper" in this context?

**Comment by justin-luoma** [comment]
🤦🏼‍♂️  with in the SDKs that everyone uses. Like the [pico sdk](https://github.com/raspberrypi/pico-sdk), and arduino. Not some bs experimental build.

**Comment by Gadgetoid** [comment]
Pico SDK *itself* is still in flux, with multiple in-development changes to the wireless drivers at our request (that incidentally directly benefit the Arduino core https://github.com/earlephilhower/arduino-pico/issues/2608). It is, necessarily, experimental.

While we have no explicit code of conduct, your attitude is unprofessional, unhelpful and unwarranted. This is GitHub not Call of Duty.
